version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "chanmgeme"
       MYSQL_DATABASE: "phprecipebook"
       MYSQL_USER: "phprecipebook"
       MYSQL_PASSWORD: "changeme-userpw"


   web:
     depends_on:
       - db
     build: .
     ports:
       - "80:80"
     restart: always
     volumes:
#      - /tmp/SetupController:/var/www/html/Controller/SetupController.php
