name: phprecipebook

services:

  php:
    image: ilveroluca/phprecipebook:v7.0_cv0.1
    user: www-data:www-data

    env_file: recipebook.env

    environment:
       DEBUG: ${DEBUG:-false}
       #APP_NAME: "PHPRecipeBook"
       #APP_ENCODING: "UTF-8"
       #APP_DEFAULT_TIMEZONE: "UTC"

    ports:
      - "8080:8080"

    tmpfs:
      - /var/www/html/tmp:mode=750,uid=33,gid=33
      - /var/www/html/logs:mode=750,uid=33,gid=33

    post_start:
      - command: ["/bin/sh", "-c", "echo 'post_start: starting migrations' >&2 && /var/www/html/bin/cake migrations migrate"]

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8001:8080
    profiles: ["debug"]
