
INSERT INTO ethnicities (name) VALUES ('American');
INSERT INTO ethnicities (name) VALUES ('Chinese');
INSERT INTO ethnicities (name) VALUES ('German');
INSERT INTO ethnicities (name) VALUES ('Greek');
INSERT INTO ethnicities (name) VALUES ('Italian');
INSERT INTO ethnicities (name) VALUES ('Japanese');
INSERT INTO ethnicities (name) VALUES ('Mexican');
INSERT INTO ethnicities (name) VALUES ('Middle Eastern');
INSERT INTO ethnicities (name) VALUES ('None');
INSERT INTO ethnicities (name) VALUES ('Slavic');

INSERT INTO units (id,name,abbreviation) VALUES (1,'Unit','ea');
INSERT INTO units (id,name,abbreviation) VALUES (2,'Slice','sli');
INSERT INTO units (id,name,abbreviation) VALUES (3,'Clove','clv');
INSERT INTO units (id,name,abbreviation) VALUES (4,'Pinch','pn');
INSERT INTO units (id,name,abbreviation) VALUES (5,'Package','pk');
INSERT INTO units (id,name,abbreviation) VALUES (6,'Can','cn');
INSERT INTO units (id,name,abbreviation) VALUES (7,'Drop','dr');
INSERT INTO units (id,name,abbreviation) VALUES (8,'Bunch','bn');
INSERT INTO units (id,name,abbreviation) VALUES (9,'Dash','ds');
INSERT INTO units (id,name,abbreviation) VALUES (10,'Carton','ct');
INSERT INTO units (id,name,abbreviation) VALUES (11,'Cup','c');
INSERT INTO units (id,name,abbreviation) VALUES (12,'Tablespoon','T');
INSERT INTO units (id,name,abbreviation) VALUES (13,'Teaspoon','t');
INSERT INTO units (id,name,abbreviation) VALUES (14,'Pound','lb');
INSERT INTO units (id,name,abbreviation) VALUES (15,'Ounce','oz');
INSERT INTO units (id,name,abbreviation) VALUES (16,'Pint','pt');
INSERT INTO units (id,name,abbreviation) VALUES (17,'Quart','q');
INSERT INTO units (id,name,abbreviation) VALUES (18,'Gallon','gal');
INSERT INTO units (id,name,abbreviation) VALUES (19,'Milligram','mg');
INSERT INTO units (id,name,abbreviation) VALUES (20,'Centigram','cg');
INSERT INTO units (id,name,abbreviation) VALUES (21,'Gram','g');
INSERT INTO units (id,name,abbreviation) VALUES (22,'Kilogram','kg');
INSERT INTO units (id,name,abbreviation) VALUES (23,'Milliliter','ml');
INSERT INTO units (id,name,abbreviation) VALUES (24,'Centiliter','cl');
INSERT INTO units (id,name,abbreviation) VALUES (25,'Liter','l');
INSERT INTO units (id,name,abbreviation) VALUES (26,'Deciliter','dl');
INSERT INTO units (id,name,abbreviation) VALUES (27,'Tablespoon_m','tbsp');
INSERT INTO units (id,name,abbreviation) VALUES (28,'Teaspoon_m','tsp');


INSERT INTO locations (name) VALUES ('Alcohol');
INSERT INTO locations (name) VALUES ('Bakery');
INSERT INTO locations (name) VALUES ('Baking needs');
INSERT INTO locations (name) VALUES ('Beans');
INSERT INTO locations (name) VALUES ('Bread');
INSERT INTO locations (name) VALUES ('Breakfast bars');
INSERT INTO locations (name) VALUES ('Candy');
INSERT INTO locations (name) VALUES ('Canned Fruit');
INSERT INTO locations (name) VALUES ('Canned Meat &amp; Fish');
INSERT INTO locations (name) VALUES ('Canned Vegetables');
INSERT INTO locations (name) VALUES ('Coffee, Tea &amp; Cocoa');
INSERT INTO locations (name) VALUES ('Condiments');
INSERT INTO locations (name) VALUES ('Cookies');
INSERT INTO locations (name) VALUES ('Crackers');
INSERT INTO locations (name) VALUES ('Dairy');
INSERT INTO locations (name) VALUES ('Deli');
INSERT INTO locations (name) VALUES ('Drink mix');
INSERT INTO locations (name) VALUES ('Facial Tissue');
INSERT INTO locations (name) VALUES ('Food Storage');
INSERT INTO locations (name) VALUES ('Free');
INSERT INTO locations (name) VALUES ('Frozen Foods');
INSERT INTO locations (name) VALUES ('HABA');
INSERT INTO locations (name) VALUES ('Hand Soap');
INSERT INTO locations (name) VALUES ('Hot &amp; Cold Cereal');
INSERT INTO locations (name) VALUES ('Household Cleaners');
INSERT INTO locations (name) VALUES ('Juice &amp; Cocktail');
INSERT INTO locations (name) VALUES ('Kosher/Ethnic');
INSERT INTO locations (name) VALUES ('Laundry Detergents');
INSERT INTO locations (name) VALUES ('Meat');
INSERT INTO locations (name) VALUES ('Natural &amp; Organic');
INSERT INTO locations (name) VALUES ('Oil/Vinegar/Dressings');
INSERT INTO locations (name) VALUES ('Pancakes &amp; Syrup');
INSERT INTO locations (name) VALUES ('Paper Serving Ware');
INSERT INTO locations (name) VALUES ('Pasta &amp; Sauce');
INSERT INTO locations (name) VALUES ('Peanut Butter/Jelly/Honey');
INSERT INTO locations (name) VALUES ('Produce');
INSERT INTO locations (name) VALUES ('Rice');
INSERT INTO locations (name) VALUES ('Salty Snacks &amp; Chips');
INSERT INTO locations (name) VALUES ('Seafood');
INSERT INTO locations (name) VALUES ('Soda pop');
INSERT INTO locations (name) VALUES ('Soup');
INSERT INTO locations (name) VALUES ('Spices');
INSERT INTO locations (name) VALUES ('Toilet Paper');

INSERT INTO base_types (name) VALUES ('Beef');
INSERT INTO base_types (name) VALUES ('Bread');
INSERT INTO base_types (name) VALUES ('Egg');
INSERT INTO base_types (name) VALUES ('Fruit');
INSERT INTO base_types (name) VALUES ('Grain');
INSERT INTO base_types (name) VALUES ('Lamb');
INSERT INTO base_types (name) VALUES ('Other');
INSERT INTO base_types (name) VALUES ('Pasta');
INSERT INTO base_types (name) VALUES ('Pork/Ham');
INSERT INTO base_types (name) VALUES ('Poultry');
INSERT INTO base_types (name) VALUES ('Seafood');
INSERT INTO base_types (name) VALUES ('Vegetable');

INSERT INTO preparation_times (name) VALUES ('0 Minutes');
INSERT INTO preparation_times (name) VALUES ('1-10 Minutes');
INSERT INTO preparation_times (name) VALUES ('10-30 Minutes');
INSERT INTO preparation_times (name) VALUES ('30-60 Minutes');
INSERT INTO preparation_times (name) VALUES ('60+ Minutes');

INSERT INTO difficulties (name) VALUES ('Easy');
INSERT INTO difficulties (name) VALUES ('Intermediate');
INSERT INTO difficulties (name) VALUES ('Difficult');
INSERT INTO difficulties (name) VALUES ('Expert');

INSERT INTO courses (name) VALUES ('Breakfast');
INSERT INTO courses (name) VALUES ('Snack');
INSERT INTO courses (name) VALUES ('Lunch');
INSERT INTO courses (name) VALUES ('Appetizer');
INSERT INTO courses (name) VALUES ('Side Dish');
INSERT INTO courses (name) VALUES ('Entree');
INSERT INTO courses (name) VALUES ('Dessert');
INSERT INTO courses (name) VALUES ('Beverage');

INSERT INTO meal_names (name) VALUES ('Breakfast');
INSERT INTO meal_names (name) VALUES ('Brunch');
INSERT INTO meal_names (name) VALUES ('Lunch');
INSERT INTO meal_names (name) VALUES ('Afternoon Snack');
INSERT INTO meal_names (name) VALUES ('Dinner');
INSERT INTO meal_names (name) VALUES ('Dessert');

INSERT INTO price_ranges (name) VALUES ('$0-$10');
INSERT INTO price_ranges (name) VALUES ('$10-$15');
INSERT INTO price_ranges (name) VALUES ('$15-$20');
INSERT INTO price_ranges (name) VALUES ('$20-$25');
INSERT INTO price_ranges (name) VALUES ('$25-$30');
INSERT INTO price_ranges (name) VALUES ('$30+');

INSERT INTO preparation_methods (name) VALUES ('Slow cooker');
INSERT INTO preparation_methods (name) VALUES ('BBQ');
INSERT INTO preparation_methods (name) VALUES ('Microwave');
INSERT INTO preparation_methods (name) VALUES ('Canning');

