INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'flour, wheat', '', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'flank steak', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'emory boards', '', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bok choy', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'water', '', 20, 11, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'egg', '', 15, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mussels', '', 39, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lime', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fennel seed', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vinegar, balsamic', '', 31, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'spanish rice', 'packet special', 37, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mozzarella grated cheese', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bologna', '', 29, 2, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dill', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cream cheese', 'Philadelphia', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'garlic', 'fresh', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cumin', 'ground', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oatmeal', 'Quaker instant', 24, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'semi-sweet chocolate chips', 'Nestle', 3, 5, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'banana', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'green beans, frozen', '', 21, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lemon juice', '', 26, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'basil leaves, dried', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cereal', '', 24, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'artichoke, canned', '', 10, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'allspice', 'ground', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'milk', '2 %', 15, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'coffee beans', '', 11, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'hazelnut liquor', '', 1, 11, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'hand soap', '', 23, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'sesame oil', '', 31, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'parsley flakes', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'egg noodles', '', 34, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'crescent rolls', 'Pillsbury', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'honey', 'in the bear!', 35, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ketchup', 'Hunts', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'olive oil', 'extra virgin', 31, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'parmesan cheese', 'grated', 16, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'buttermilk', '', 15, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'parsley, fresh', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'italian bread', '', 2, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lemon peel', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bouillon, beef', '', 41, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chicken breast', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'coffee filters', '', 11, 5, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dish soap', '', 25, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mozzarella slices', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mexican grated cheese', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'clearasil', '', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'brown sugar', 'light brown', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cream of mushroom soup', 'Campbells Great for Cooking (blue label)', 41, 6, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cream of chicken soup', 'Cambells Great for Cooking (blue label)', 41, 6, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'green onion', 'scallion', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ginger', 'ground', 42, 13, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cranberry sauce, jellied', 'Ocean Spray', 8, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mouthwash', 'Listerine', 22, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oregano', 'leaves', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'orange juice', 'no pulp, preferably with calcium', 15, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'grape jelly', 'Welchs in the jar', 35, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bell pepper, green', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dry sherry', '', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'butter', 'salted', 15, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'granola bar', 'Quaker chocolate chip', 6, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pumpkin pie mix', 'Libbys', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cilantro, fresh', '', 36, 8, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'gladware', '', 19, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'sugar', '', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tortilla chips', '', 38, 5, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tortilla', '', 15, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vanilla extract', '', 42, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'paper towels', '', 48, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'evaporated milk', '', 3, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'garlic powder', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'graham cracker pie crust', '', 3, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'italian seasonings', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cheese crackers', 'pre-packaged snack', 13, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'monterey jack cheese', '', 15, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'napkins', '', 33, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'paprika', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'aluminum foil', '', 19, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'baking powder', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'baking soda', '', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cayenne pepper', '', 42, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cheese, cheddar', '', 15, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chili powder', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chinese five spice', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cocoa powder', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'corn starch', '', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cream of tartar', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'red wine vinegar', '', 31, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'horseradish', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'salt', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'semi-sweet baking chocolate', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rosemary', 'leaves', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'white chocolate chips', 'Nestle', 3, 5, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tea bags', 'herbal', 11, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'teriyaki sauce', 'Kikkoman marinade', 27, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vegetable oil', '', 31, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pork chop', '', 29, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'apple', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chickpeas', 'in the can', 51, 6, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'carrot', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'beef rump roast', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'turkey, deli', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dryer sheets', '', 28, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mushroom, portobello', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'plastic spoons', '', 33, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'plastic wrap', '', 57, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'raspberry preserves', '', 35, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ricotta cheese', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'sandwich bags', '', 57, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'windex', '', 25, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'sponge', '', 25, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'summer squash', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'potato, sweet', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'trash bags', '', 57, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'kitchen boutique', '', 42, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lemon', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oreo cookies', '', 13, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bouillon, vegetable', '', 41, 11, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'curry', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'couscous', '', 37, 11, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bell pepper, red', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bar soap', '', 23, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chapstick', '', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cotton balls', '', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tortellini', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tarragon', '', 36, 8, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fajita seasoning mix', '', 27, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'alfalfa sprouts', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'swiss cheese', '', 15, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bacon', 'precooked', 29, 2, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomato sauce', 'Hunts', 34, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vinegar, champagne', '', 31, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'unsweetened baking chocolate', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bread', 'wheat sandwich', 5, 2, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'sour cream', '', 15, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chives', '', 36, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'hot sauce', '', 51, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chicken, deli', '', 29, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'peas', 'frozen', 21, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lamb', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'kleenex', '', 18, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'active dry yeast', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cornmeal', '', 3, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'marachino cherries', '', 21, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mustard, deli', '', 12, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'worcestershire sauce', '', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dry mustard', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'applesauce', 'individual packets; natural', 8, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'avocado', 'ripe when soft if squeezed; place in sun to ripen', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bacon bits', 'made from REAL bacon only!', 31, 12, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bagel', 'Thomas Toaster Bagels', 5, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pumpkin pie spice', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'beefy onion soup mix', 'Liptons', 41, 5, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'yam', 'red', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pepper, black', 'ground', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'trout, fillet', '', 39, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bourbon whiskey', '', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'broccoli', 'florets', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pistachios', 'shelled', 36, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chocolate syrup', 'hersheys', 11, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'walnuts', 'chopped', 3, 11, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cucumber ranch dressing', 'Kraft', 31, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'floss', 'mint waxed', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ginger root', 'throw away the first piece you cut off every time you use it', 36, 2, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cinnamon', 'ground', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cloves', 'ground', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rice, arborio', '', 37, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'macaroni & cheese', 'Kraft classic', 46, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mayonnaise', 'Helmanns', 31, 17, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pierogies', 'West Side Market', 29, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'peanut butter', 'Jiffy', 35, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'powdered sugar', 'confectioners sugar', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rice vinegar', 'NOT a dressing', 27, 11, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'zucchini', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'yogurt', 'Yoplait', 15, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'whipped cream', 'sshhhhhh', 15, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bouillon, chicken', '', 41, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'parchment paper', '', 57, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'turmeric', 'Indian Saffron', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomato', 'garden vine, hothouse, or salad', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'potato, fingerling', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'shortening', 'Crisco', 31, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'smoked salmon', 'lox', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'orange', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'stuffing mix', 'Stovetop', 45, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'kirsch', 'cherry liquor', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mushroom, shitake', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'creole mustard', '', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'beef chuck roast', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bay leaves', '', 42, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'water chestnuts', 'canned & sliced', 27, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'wasabi', 'Japanese horseradish', 27, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pickled ginger', '', 51, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'soy sauce', 'San-J', 27, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'croissants', '', 2, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomato paste', 'Hunts', 34, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'corn, frozen', '', 21, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cucumber', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'flour, white', 'white sifted all-purpose', 3, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cabbage', 'head of cabbage', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'shallot', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'soba noodle', 'wheat based japanese noodle', 27, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ravioli, mushroom', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'coriander', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pita bread', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomato, grape', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'french bread', '', 2, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'thyme', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'spaetzle', '', 34, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lettuce', '', 36, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'potato, baking', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pesto sauce with basil', 'In the jar', 34, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oyster sauce', '', 51, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mushroom, button', 'Creekside Moonlight mushrooms', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'green beans, canned', 'no salt', 10, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomatos, stewed and canned', '', 10, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'half and half', '', 15, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'clams, canned', 'minced or chopped', 9, 6, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'potato, red', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chicken, roasting', '', 29, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'onion, yellow', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'onion, white', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'croutons, seasoned', '', 31, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rice, sushi', '', 37, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'seaweed, sushi', 'sheet of seaweed', 27, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'syrup, pancake', 'for pancakes, waffles, & french toast', 32, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rice, wild', '', 37, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'rice, white', '', 37, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'almond butter', '', 35, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bread crumbs', '', 45, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bamboo shoots', 'canned and sliced', 27, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tomato, roma', 'plum tomatoes', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vinegar, white', '', 31, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ice cream', '', 21, 17, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tuna', 'canned', 9, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'heavy whipping cream', 'a.k.a whipping cream', 15, 17, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'wax paper', '', 57, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'turkey, roasting', 'Fresh Free Range', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lambrusco wine', 'Riunite', 1, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pinot grigio', '', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'basil leaves, fresh', '', 36, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chardonnay wine', 'Haywood (2001); Vinters Select', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fruit cup', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tilapia', 'fish', 39, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'peppercorn', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'marsala wine', 'Taylor', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'juice boxes', '', 26, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'onion, red', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ham, baked', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'madeira wine', '', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cilantro, dried', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'asparagus', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'shrimp, frozen', '', 21, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'anchovies', '', 9, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'olives', 'black', 12, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'capers', '', 12, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'munster cheese', '', 15, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dijon mustard', '', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cheese, asiago', '', 16, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tequila', 'gold', 1, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bell pepper, yellow', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'jalapeno', '', 36, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fettucine, spinach', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'penne, whole wheat', '', 34, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bisquick', '', 3, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'nutmeg', '', 42, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'poppyseed', '', 42, 13, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ground beef', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'orzo', '', 34, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vinegar, white wine', '', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'gatorade', '', 26, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ice cream sandwiches', '', 21, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'angel hair pasta', '', 34, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'linguine', '', 34, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'spaghetti', '', 34, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tabouli', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'dishwasher soap', '', 25, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'vitamins', '', 22, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'chocolate bar', '', 7, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'salmon, canned', 'red sockeye or pink sockeye', 9, 6, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'seasoned bread crumbs', '', 45, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ranch dressing', 'HIdden Valley bacon ranch', 31, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'marjoram', '', 42, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'garam masala', 'spice', 51, 13, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cauliflower', 'frozen', 21, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'Italian dressing mix', 'good seasons', 31, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'ziti', '', 34, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'milk, whole', '', 15, 18, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oyster crackers', '', 52, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pudding', 'chocolate!', 15, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'bean, black', '', 10, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'beer, stout', '', 1, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'butter, unsalted', '', 15, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'barbecue sauce', '', 12, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'potato, yukon gold', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'tahini', '', 16, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lamb, ground', '', 29, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mint, fresh', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'flatbread', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pomegranate molasses', '', 51, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mushroom, cremini', 'baby portabella', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fettuccine', '', 34, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cheese, romano', '', 16, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'taco, seasoning mix', '', 51, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'refried beans, black', '', 51, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'jalapeno, jared', '', 51, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'oats, rolled', '', 3, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cranberry, dried', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'fennel, bulb', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'italian sausage', '', 29, 14, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'spinach', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'wine, red', '', 1, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'apricot, dried', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pork tenderloin', '', 29, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'apple cider', '', 36, 1, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'hamburger buns', '', 5, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'blueberries', '', 36, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'eggplant', '', 36, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'lasagna noodles', '', 34, 1, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'pepperoni', '', 29, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'strawberry', 'fresh', 36, 16, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'mustard, yellow', '', 12, 15, 0, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'gouda, smoked', '', 16, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'cherries, dried', '', 36, 15, 1, 'usa', 1);
INSERT INTO ingredients (name, description, location_id, unit_id, solid, system, user_id) VALUES ( 'halibut', '', 39, 14, 1, 'usa', 1); 
